"""add_student_min_max_ages_to_course

Revision ID: 09f9304823ec
Revises: d735bb428b1e
Create Date: 2026-09-12 23:50:52.852597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "09f9304823ec"
down_revision: Union[str, Sequence[str], None] = "d735bb428b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("min_student_age", sa.Integer(), nullable=False))
    op.add_column("course", sa.Column("max_student_age", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "max_student_age")
    op.drop_column("course", "min_student_age")
    # ### end Alembic commands ###
