"""add table educational_unit

Revision ID: bb0147370acb
Revises: fa7177860c74
Create Date: 2026-09-27 23:55:08.127869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bb0147370acb"
down_revision: Union[str, Sequence[str], None] = "fa7177860c74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "educational_unit",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("zip_code", sa.String(length=8), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("number", sa.String(length=10), nullable=False),
        sa.Column("complement", sa.String(length=100), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "course",
        sa.Column(
            "educational_unit_id",
            sa.BINARY(length=16),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None, "course", "educational_unit", ["educational_unit_id"], ["id"]
    )
    op.add_column(
        "user",
        sa.Column(
            "educational_unit_id",
            sa.BINARY(length=16),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "user", "educational_unit", ["educational_unit_id"], ["id"]
    )
    op.add_column(
        "user_type",
        sa.Column("register_educational_unit", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_type", "register_educational_unit")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "educational_unit_id")
    op.drop_constraint(None, "course", type_="foreignkey")
    op.drop_column("course", "educational_unit_id")
    op.drop_table("educational_unit")
    # ### end Alembic commands ###
