"""rename_user_course_to_enrollment

Revision ID: c7234d208ca0
Revises: 09f9304823ec
Create Date: 2026-09-13 00:06:53.023053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c7234d208ca0"
down_revision: Union[str, Sequence[str], None] = "09f9304823ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrollment",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_as_cs",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("user_course")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_course",
        sa.Column(
            "active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("user_course_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("user_course_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_as_cs",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("enrollment")
    # ### end Alembic commands ###
