"""alter_log_broadcast_message_docs_base64_to_mediumtext

Revision ID: d735bb428b1e
Revises: d3ec3cf81c10
Create Date: 2026-09-12 22:28:05.215430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d735bb428b1e"
down_revision: Union[str, Sequence[str], None] = "d3ec3cf81c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log_broadcast_message",
        "document_1_base64",
        existing_type=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "log_broadcast_message",
        "document_2_base64",
        existing_type=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log_broadcast_message",
        "document_2_base64",
        existing_type=mysql.MEDIUMTEXT(),
        type_=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        existing_nullable=False,
    )
    op.alter_column(
        "log_broadcast_message",
        "document_1_base64",
        existing_type=mysql.MEDIUMTEXT(),
        type_=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
