"""add log_access table

Revision ID: eff6b7d4d827
Revises: c7234d208ca0
Create Date: 2026-09-13 15:28:53.845925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eff6b7d4d827"
down_revision: Union[str, Sequence[str], None] = "c7234d208ca0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_access",
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("origin_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_access")
    # ### end Alembic commands ###
